### ISSUE TITLE
rosservice call /agent_x/update_goal  ERROR: Service [/agent_x/update_goal] is not available.

### ISSUE THREAD

**Issue by 544211707** [swiz23/SOLOMON_WIZNITZER_FULLTIME#1]
Thank you for your open source! Why did I make the following mistakes?
`xxx:~$ rosservice call /agent_x/update_goal

ERROR: Service [/agent_x/update_goal] is not available.
`

**Comment by 544211707** [comment]
Problem solved, you can use the following code:
`rosservice call /agent_1/update_goal [1,1,0]`

**Comment by swiz23** [comment]
looks like you solved it! closing 2 years later lol
